version: 0.2

phases:
    install:
        commands: 
            - echo started...
            
    pre_build:
        commands: 
            - echo building npm
            - npm install

    build:
        commands:
            - echo deployment started..
            - sam build
            - sam package --template-file template.yaml --s3-bucket greetme-cicd --output-template-file packaged.yaml
            - sam deploy --template-file packaged.yaml --stack-name mystack --capabilities CAPABILITY_IAM
    
    post_build:
        commands: 
            - echo deployment complete..