version: 0.2

phases:
    install:
        commands: 
            - echo started...
            
    pre_build:
        commands: 
            - echo building npm
            - npm install

    build:
        commands:
            - echo deployment started..
            - sam deploy --stack-name greetMe-api 
    
    post_build:
        commands: 
            - echo deployment complete..