AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Url shortener with SAM

Resources:
    urlShortner:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            MemorySize: 128
            Timeout: 10
            Runtime: nodejs12.x
            Events:
                Shortener:
                    Type: Api
                    Properties:
                        Path: /shorten
                        Method: POST
    srcBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: ygr
            WebsiteConfiguration:
                IndexDocument: index.html

    SampleBucketPolicy: 
        Type: AWS::S3::BucketPolicy
        Properties: 
            Bucket: 
                Ref: "srcBucket"
            PolicyDocument: 
                Statement: 
                    - 
                        Action: "*"
                        Effect: "Allow"
                        Resource: 
                            -   arn:aws:s3:::ygr
                            -   arn:aws:s3:::ygr/*
                        Principal: "*"